#############################################################
## NOT FOR PRODUCTION USE.                                 ##
## THE CONTENT OF THIS FILE IS FOR LEARNING PURPOSES ONLY  ##
## created by David Surey, Amazon Web Services, 2020       ##
#############################################################

- name: setup service account for x-ray
  delegate_to: "{{ EKSBastionInstancePublicIP }}"
  shell: >
    eksctl create iamserviceaccount \
    --name xray-daemon \
    --namespace kube-system \
    --cluster "{{ eksexample_clustername }}" \
    --attach-policy-arn arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess \
    --approve \
    --region {{ eksexample_region }} \
    --override-existing-serviceaccounts

- name: label the xray service-account 
  delegate_to: "{{ EKSBastionInstancePublicIP }}"
  shell: > 
    kubectl label serviceaccount xray-daemon app=xray-daemon -n kube-system --overwrite

- name: Deploy X-ray
  delegate_to: "{{ EKSBastionInstancePublicIP }}"
  community.kubernetes.k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', './k8s/x-ray/eks-xray-{{ item }}.manifest.yaml') | from_yaml }}"
  loop:
    - clusterrolebinding
    - configmap
    - deamonset
    - service
