apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ item }}
  namespace: eksdemo
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ item }}
  targetCPUUtilizationPercentage: 30