apiVersion: v1
kind: Service
metadata:
  name: eksdemo-frontend
  namespace: eksdemo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: eksdemo-frontend