apiVersion: v1
kind: Service
metadata:
  name: xray-service
  namespace: kube-system
spec:
  selector:
    app: xray-daemon
  clusterIP: None
  ports:
  - name: incoming
    port: 2000
    protocol: UDP